# This is a basic workflow to help you get started with Actions

name: JSR
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets. REPO_ACCESS_TOKEN }}
          repository: santhoshshetty/GithubActions
          event-type: SMT_Event
          client-payload: '{"github": ${{ toJson(github) }}}'

